Fantom-foundation/Norma

Dockerfile
Makefile
driver/node/opera.go
driver/node/opera_test.go
scripts/run_sonic.sh

> Note: This replaces the old build process:
> - previously was build go-opera-norma by 1. cloning carmen, tosca 2. build carmen locally (See [update-to-opera-norma-aa88d69](https://github.com/Fantom-foundation/Norma/tree/rapol/update-sonic/update-to-opera-norma-aa88d69)
> - current build is simply cloning carmen via go.mod
> 
> In future update, both should be available as an option. 
> Afterwards, compatibility of both (or more) client types simultaneously in the same scenarios.
No longer applicable. Will only support client that uses go.mod instead of submodules.

Update Norma to Sonic 57863ea

---

.gitmodules

- Update to latest sonic version
- submodule now uses `https://github.com/Fantom-foundation/Sonic.git` instead of `git@github.com:Fantom-foundation/Sonic.git`

Update Sonic Version

---

driver/executor/executor.go
driver/parser/check.go
driver/parser/check_test.go
driver/parser/parser.go
driver/parser/parser_test.go

Changes related to cheat as found here: https://github.com/Fantom-foundation/Norma/issues/190
Add `cheat` config to Scenario - so that we can simulate cheating to artificially start epoch sealing 
**cheat = start 2 validators with same key at the same time**

YML Update: Cheat

---

Dockerfile

The following warning is found when running `make`
```
1 warning found (use --debug to expand):
- JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 51)
```
Further discussion:
https://docs.docker.com/reference/build-checks/json-args-recommended/
This may be why the containers don't respond to `SIGTERM` and `SIGKILL` correctly.

Fix JSONArgsRecommended warning on make

---

driver/executor/executor.go
driver/parser/check.go
driver/parser/check_test.go
driver/parser/parser.go
driver/parser/parser_test.go

Changes related to node.Genesis as found here: https://github.com/Fantom-foundation/Norma/issues/190
Add `genesis` config to Node - so that we can schedule genesis import to/export from a node.

YML Update: node.Genesis

---

driver/executor/executor.go
driver/parser/check.go
driver/parser/check_test.go
driver/parser/parser.go
driver/parser/parser_test.go

Changes related to events as found here: https://github.com/Fantom-foundation/Norma/issues/190
Add `event` config to Node - so that we can schedule event import to/export from a node. 
**need to revise event name??**

YML Update: Event

---

driver/network_mock.go
load/app/app_test.go
load/controller/rpc_test.go

- `gomock` reverted to previously used (from `github `and not `go.uber...`)
- test for app/rpc now uses updated new account func

Bugfix for PR218

---

CI.jenkinsfile

Currently, when reusing GCP VM, client submodule remains as causes gofmt check to fail.
This is a workaround to skip the directory for the time being.

Gofmt now skip client directory

---

driver/norma/run.go

Currently, the monitoring artifacts are defaulted to `/tmp/norma_data_<label>_<random>`.
This add a symlink so that `/tmp/norma_data_<label>_latest` -> `/tmp/norma_data_<label>_<random>`.

[QoL] Added symlink to latest run

---

RT.jenkinsfile
driver/norma/run.go

- Each scenario now has its own label (`A1.xxx.yml` now runs with flag `--label A1`)
- As an option, output directory after a run can be configured using the flag `--output-directory <path>` or `-o <path>`.
- If unconfigured, defaults to `/tmp/` as before
- Additionally, a symlink is created so that `/path/to/output/norma_data_<label>_latest)` always links to the latest run.
- Jenkins now archive the monitoring folder whenever the scenario run is successful

[QoL] RT.jenkinsfile now collect monitoring as artifact

---

driver/monitoring/node/block_progress.go
driver/monitoring/node/block_progress_test.go
driver/monitoring/record.go
driver/monitoring/types.go
driver/norma/run.go

BlockHeight monitoring now tracks Epoch in addition to BlockHeight (and thus renamed BlockStatus).
`[B B B]` now reads `[E/B E/B E/B]` where B = Block Height and E = Epoch Number
Example of log:
```2024/08/07 10:45:05 Nodes: 3, block heights: [2/1 2/1 2/1], tx/s: [], txs: N/A, gas: N/A, block processing: []```

Epoch is also logged via BlockHeight monitoring

---

driver/executor/executor.go
driver/network.go
driver/network/local/local.go
driver/parser/parser.go
scenarios/small_new_cheater.yml
scenarios/small_new_validator.yml

Add option to start validator as cheater. This is reached by starting two nodes with same private key. 
TODO: timing of node start still needs to be dialed in and might never be 100% deterministic in causing the cheater.

Add double sign cheater

---

RT.jenkinsfile

```
post {
always {
script {
def artifacts = ["*.yml", "*.csv", "*.log", "*.html"]
uploadArtifacts(artifacts)
}
}
}
```
should now reads:
```
post {
always {
uploadArtifacts(["*.yml", "*.csv", "*.log", "*.html"])
}
}
```

Collapse upload artifacts

---

Dockerfile

This PR updates build process of Norma for the docker environment in the way that Norma itself is build inside the container. 
Previous version was error prone, because guest and host systems may run (and often run) different architectures. When Norma is build at host system and copied into the container, it cannot be executed in the container once it runs on a different platform.
Example: Norma was build on a dev Mac, i.e. arm64 while the docker container runs amd64.

builds norma itself for docker in the build container

---

driver/network.go
driver/network/local/local.go
driver/node/opera.go
driver/norma/run.go

This PR removes two flags that are no longer effective (both options are hard-coded in the client):
- `--vm-impl` ... switch between different VM implementations; Sonic uses LFVM for everything but tracing
- `--db-impl` ... switch between different DB implementations; Sonic always uses Carmen

Remove misleading VM and DB flags

---

Dockerfile

This change can save minutes of build time in the development loop since dependencies are downloaded only once and then cached by docker as long as the `go.mod` files do not change.

Add downloading of dependency as an extra docker build step

---

analysis/report/single_eval_report.Rmd
driver/docker/docker.go
driver/monitoring/logreader.go
driver/monitoring/network/block_metrics.go
driver/monitoring/node_log_provider_test.go
driver/monitoring/testdata.go
driver/parser/parser.go
scripts/run_sonic_privatenet.sh

This PR adds tracking support for two new metrics:
- the gas `base-fee` prices on a per-block level, measured in `wei/gas`
- the gas throughput on a per-block level, measured in `gas/s` 
Example:

Add tracking of Gas rates and Base-Fees

---

scenarios/test/baseline_check.yml

Fixes the number of users participating in the baseline check.
Before this change, the entire load was issued by a single user. A single user, however, is limited in the number of transactions that are accepted per second. With this change, the incoming load in the network is as specified.

Fix number of users in baseline test case

---

load/app/context.go

This PR updates the funding of accounts to process fund-distribution in batches of at most 128 accounts. This ensures that individual transactions do not exceed the gas limit of single transactions in cases where multiple hundred accounts are required.

Perform account funding in batches

---

driver/checking/block_height.go
driver/checking/blocks_hashes.go
driver/executor/executor.go
driver/executor/executor_test.go
driver/norma/run.go
load/app/context.go
scenarios/test/nodes_net_consistency.yml

This PR updates when network consistency is executed. 
It used to be executed at the end of scenario, but unfortunetly at that moment all dyanmic nodes are alreay shutdown. The only nodes still running are static validators. 
This PR schedules consistency check as an event just before the end (1s) of execution. At this moment all nodes runnign till the end of experiment, are still active. 
This change still misses nodes that were halted before end of scenario, we could consider adding an extra configuration to schedule the consistency check at any time.

puts network consistency check before shutdown

---

load/app/account.go
load/app/account_test.go

This PR fixes address factory to generate uniq addresses when more factorires is used. 
The factories had application ID as an argument, but this ID was not used. It caused that non-unique addresses were generated when more applications were deployed in an experiment. 
This PR fixes this problem by including application ID and feed ID in the address.

generates uniq addresses for multiple applications
